### ISSUE TITLE
Error with compiling code

### ISSUE THREAD

**Issue by adam-short** [JamesRandall/FunctionMonkey#6] opened 2018-08-16 06:06 UTC
When attempting to compile I was first greeted with the following:
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 74.92 ms for /Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj.
  ICE -> /Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll
  No executable found matching command "dotnet-/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/..\..\tools\netcoreapp2.0\FunctionMonkey.Compiler.dll"
/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(10,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/..\..\tools\netcoreapp2.0\FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 1. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]

Build FAILED.

/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(10,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/..\..\tools\netcoreapp2.0\FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 1. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.83

```
After a bit of digging around, I found that inside of `netstandard1.0/FunctionMonkey.Compiler.targets` I was specifying this path with:
```
    <FunctionCompilerExe Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' OR '$(TargetFrameworkIdentifier)' == '.NETStandard'">dotnet "$(MSBuildThisFileDirectory)..\..\tools\netcoreapp2.0\FunctionMonkey.Compiler.dll"</FunctionCompilerExe>

```
Surprisingly, the direction of those slashes was actually important - when I reversed them, I located the DLL correctly (I verified in the terminal that it was in fact at that location too) 
```
    <FunctionCompilerExe Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' OR '$(TargetFrameworkIdentifier)' == '.NETStandard'">dotnet "$(MSBuildThisFileDirectory)../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll"</FunctionCompilerExe>

```
However, this might of fixed that issue but it uncovered a much more troublesome issue that I can't fix.
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 66.52 ms for /Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj.
  ICE -> /Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll
  
  Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at FunctionMonkey.ConfigurationLocator.FindConfiguration(Assembly assembly) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey\ConfigurationLocator.cs:line 95
     at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 56
     at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 44
  /var/folders/ws/8qmgsd2d5qzgk18kqcr5tgb80000gn/T/tmp76d75810b305435184c34e47eb5e1137.exec.cmd: line 2: 39374 Abort trap: 6           dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"
/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(10,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 134. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]

Build FAILED.

/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(10,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.11.0-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 134. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]
    0 Warning(s)
    1 Error(s)
```
If you need any details I will happily provide. I am building a production system using this platform as I actually was going to build all of this myself before I stumbled upon the framework thanks to a tip from a mate (how lucky!!!). 

Happy to help however I can! The only potential thing I can think of is that my DLL resides within netstandard2.0, while FM.Compiler seems to be in netstandard1.0?

**Comment by JamesRandall** [comment] 2018-08-16 07:13
First - thanks for the detailed error report, I'm looking at this now. I believe I have a resolution for the path issue and the second issue is connected to some sort of assembly loading problem which is missing type information in the exception. I'll get those resolved now and while I don't think that will fix the second problem hopefully it will give us more insight.

If its still opaque at that point then I can outline how to debug FunctionMonkey (its pretty easy) and we can maybe do a screen share or share source. Whatever works best!

**Comment by adam-short** [comment] 2018-08-16 07:14
Fantastic! That would be awesome. Yeah, I am super happy to debug FM, sounds great!

**Comment by JamesRandall** [comment] 2018-08-16 07:50
A couple of new NuGet packages should be available (FunctionMonkey 0.12.1 and FunctionMonkey.Compiler 0.12.1) - could you give those a go and let me know what you find please?

The FunctionMonkeyCompilerExe property in the target file should now use / on Unix based platforms (I've not been able to try that - I do have a Mac but not with me at the moment, I've only used FunctionMonkey in "debug" mode on it so obviously this is something I need to start looking at more closely now!).

And I've put some belt and braces around the error handler for the assembly load exception. Seems its getting a null type I didn't expect.

I'm just writing up some compile and debug notes as part of the main documentation now - ought to be there anyhow.

**Comment by adam-short** [comment] 2018-08-16 22:28
Also, I can confirm that Microsoft.WindowsAzure.Storage.dll is in fact in netstandard2.0/bin.

**Comment by JamesRandall** [comment] 2018-08-17 06:37
Thanks!

The issue is to do with the version of the Microsoft.WindowsAzure.Storage assembly - because Azure Functions runs your code in process and how the extensions worked you had to match the specific versions of assemblies that the runtime was using. Severely limiting.

Fortunately they've been working on improving this but the Storage assembly is the last one to be addressed. There's some more info here:

https://github.com/Azure/Azure-Functions/issues/821

They are literally about to roll out updates to resolve this:

https://github.com/Azure/app-service-announcements/issues/129
https://github.com/Azure/app-service-announcements-discussions/issues/64

In the meantime you basically need to make sure you reference (and your dependencies reference or are compatible with) 8.6.0.

As soon as the new NuGet package is released (tonight I believe) I'll update the Function Monkey assemblies to match.

If you're interested in debugging Function Monkey / working on it / exploring it I've published some guidance over here:

https://functionmonkey.azurefromthetrenches.com/guides/contributing/debugging.html

Hopefully useful!

**Comment by adam-short** [comment] 2018-08-17 06:49
Oh wow, that is some seriously convenient timing! Thank you for all your help!

Thanks for the guidance doc too,  super interested in working on the framework. Cheers!

**Comment by JamesRandall** [comment] 2018-08-17 06:54
Thanks for your help in getting to the bottom of it and feedback, much appreciated!

I'll close this now but do let me know if you have any further issues.

**Closed by JamesRandall** 2018-08-17 06:54 UTC
